index:
    path: /
    controller: App\Controller\MainController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

settings-basic:
    path: /settings-basic
    controller: App\Controller\SettingsController::index

settings-aws:
    path: /settings-aws
    controller: App\Controller\SettingsController::aws

settings-email:
    path: /settings-email
    controller: App\Controller\SettingsController::email

statistics:
    path: /statistics