index:
    path: /
    controller: App\Controller\MainController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

settings-basic:
    path: /settings-basic
    controller: App\Controller\SettingsController::index

settings-aws:
    path: /settings-aws
    controller: App\Controller\SettingsController::aws

settings-email:
    path: /settings-email
    controller: App\Controller\SettingsController::email

statistics:
    path: /statistics
    controller: App\Controller\StatisticsController::index

brands:
    path: /brands
    controller: App\Controller\BrandsController::index

brands-add:
    path: /brands/add
    controller: App\Controller\BrandsController::add

brands-edit:
    path: /brands/{id}/edit
    controller: App\Controller\BrandsController::edit

brands-remove:
    path: /brands/{id}/remove
    controller: App\Controller\BrandsController::remove

campaigns:
    path: /campaigns
    controller: App\Controller\CampaignsController::index