index:
    path: /
    controller: App\Controller\MainController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

settings:
    path: /settings
    controller: App\Controller\SettingsController::index

statistics:
    path: /statistics